In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random

%matplotlib inline

In [2]:
def generate_training_data(n):
    x0 = np.random.rand(n)
    x1 = np.random.rand(n)
    labels = [1 if xx0<xx1 else -1 for xx0, xx1 in zip(x0, x1)]
    train_data = pd.DataFrame({'x0': x0, 'x1': x1, 'label': labels})
    return train_data

train_data = generate_training_data(100)
groups = train_data.groupby('label')
fig, ax = plt.subplots()
ax.margins(0.05) # Optional, just adds 5% padding to the autoscaling
for name, group in groups:
    ax.plot(group.x0, group.x1, marker='o', linestyle='', ms=5, label=name)
ax.legend()

plt.show()

In [3]:
def sign(x):
    if x>=0:
        return 1
    else:
        return -1
    
class Perceptron(object):
    def __init__(self, feature_len=2, lr=0.1):
        self.weights = [random.uniform(0,1) for i in range(feature_len)]
        self.lr = lr
    
    def guess(self, features):
        tot = 0
        for i in range(len(features)):
            tot += self.weights[i]*features[i]
        return sign(tot)
    
    def train(self, features, target):
        guess = self.guess(features)
        error = target - guess
        
        # tune the weights
        for i in range(len(features)):
            self.weights[i] = self.weights[i] + error * features[i] * self.lr

In [4]:
train_data = generate_training_data(100)
p = Perceptron(lr=0.1)

def get_squared_error(train_data, p):
    tot_error = 0
    for i, row in train_data.iterrows():
        features = [row['x0'], row['x1']]
        target = row['label']
        guess = p.guess(features)
        error = target - guess
        tot_error += error * error
    return tot_error

get_squared_error(train_data, p)

220.0

In [6]:
for i, row in train_data.iterrows():
    features = [row['x0'], row['x1']]
    target = row['label']
    p.train(features, target)
    if p.guess(features) != target:
        print get_squared_error(train_data, p), p.weights

In [57]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

class NeuralNet(object):
    def __init__(self, n_features, n_hidden, n_out):
        self.n_features = n_features
        self.n_hidden = n_hidden
        self.n_out = n_out
        
        self.weights_ih = np.random.rand(n_hidden, n_features)
        self.weights_ho = np.random.rand(n_out, n_hidden)
        self.biad_ih = np.random.rand(n_hidden)
        self.biad_ho = np.random.rand(n_out)
    
    def feedforward(self, features_array):
        features = np.array(features_array)
        hidden = sigmoid(self.weights_ih.dot(features) + self.biad_ih)
        output = sigmoid(self.weights_ho.dot(hidden) + self.biad_ho)
        return output
    
    def train(self, features_array, labels_array):
        labels = np.array(labels_array)
        outputs = self.feedforward(features_array)
        errors = labels - outputs
        hidden_errors = self.weights_ho.T.dot(errors)
        print(hidden_errors)

In [49]:
nn = NeuralNet(2, 2, 1)
nn.feedforward([1,0])

array([0.67482399])

In [58]:
nn.train([1,0], [1])

[0.10573944]


In [51]:
sigmoid(z.T)

array([0.20036597, 0.0719671 ])

In [55]:
np.random.rand(2, 3).T

array([[0.99278767, 0.61654023],
       [0.27551427, 0.30262817],
       [0.98550114, 0.66824334]])

In [53]:
z.T

array([-1.38400863, -2.55685804])